### ISSUE TITLE
AFM PDF Download Fails

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#10]
Trying to download the AFM by clicking the download button (after confirming mail address), I get redirected to yes.pep.coop.

The button link is:

https://yes.pep.coop/C3S_SCE_AFM_fuenfeusbuffenDE.pdf

I suspect there is a problem generating the PDF, thus it does not exist.

**Comment by ari-pep** [comment]
uuhm. there are three datasets for which this url would be generated. the code that is entered is for another one - and it is used as reference for bank transfers. This means that payments would be registered for a different account.

at least from the admin interface the correct pdfs are generated

This _may_ be because I had strange cookies. But it's very bad nonetheless. We have to verify this.

**Comment by ari-pep** [comment]
ok, figured it out: the part of the pdf originating from your name doesn't matter at all, `C3S_SCE_AFM_.*.pdf` is matched (well maybe not `.* `to avoid things like /)
the content is generated according to the session you have.

I think that's safe. @buffstop, do you agree?
