### ISSUE TITLE
merge upstream 5817ba4f (was: Delete test user when done)

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#68]
Please name test users something with TEST and delete them when done testing. (we have two ari registrations :-) )
Be careful deleting users in production!

**Comment by ari-pep** [comment]
This was not really a test actually: this happens when the form cannot be completed for some reason, a new session is started or even when user edits details.
 (I think I suspected something with my firefox, so switched to chromium) 

[upstream addressed this by writing to the db not before the second view is completed ](https://github.com/C3S/c3sMembership/commit/5817ba4ffa50b686975c2ec19e80469038f1726d) - will see wether that commit can be merged into our codebase

**Comment by ari-pep** [comment]
man, would've been easier to rewrite that commit by hand instead of cherry-picking it
