### ISSUE TITLE
Hover "email confirmed" date 1.1.1970

### ISSUE THREAD

**Issue by buffstop** [ari-pep/PepCoopMembership#70]
In backend:
Hovering over the "Yes" button that letzs you know the user has confirmed his email, 1.1.1970 is shown. I assume that is supposed to show the date the email has been confirmed.

My expectation might well be wrong though. Maybe it is the date a reminder has been sent (which did not happen yet for the affected users).

**Repro:**
- Login to backen
- In dashboard, hover the curser over one of the "Yes" buttons in collumn "email conf'd?"

**Expected:**
Date of email confirmation is displayed.

**Actual:**
1.1.1970 is displayed.

**Comment by ari-pep** [comment]
I turned the button into a light. It doesn't have a mouseover
The button was for the misleading mail_mail_confirmation route anyway (for people registering on another PC so they were not asked to enter a password...) and the mouseover was for when the mail_mail_confirmation was sent out.

If you care about a metric like this, I think it would be better to show the number of days since the initial registration happened and when was last acted about it (mailto link klicked, e.g.)
